apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  selector:
    app: spc
    env: dev
    version: v3.4.0
  ports:
    - type: nodePort
      port: 8080
      targetPort: 8080
      nodePort: 31000