apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: task-2-svc
  labels:
    app: spc
    env: dev
    version: v3.4.0
spec:
  minReadySeconds: 3
  replicas: 3
  selector:
    matchLabels:
      app: spc
      env: dev
      version: v3.4.0
  template: 
    metadata:
      name: task-2-pod
      labels:
        app: spc
    spec:
      containers:
        - name: task-2-con
          image: shaikkhajaibrahim/spcjan2024:1.0
          ports:
            - containerPort: 8080
              



    