apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: mysql
spec:
  containers:
  - name: pv-sql
    image: mysql
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: mysql123
      - name: MYSQL_DATABASE
        value: mysql
      - name: MYSQL_USER
        value: mysql
      - name: MYSQL_PASSWORD
        value: mysql123
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3306

  
