apiVersion: apps/v1
kind: Deployment
metadata:
  name: "task2_deploy"
spec:
  minReadySeconds: 3
  replicas: 10
  selector:
    matchLabels:
      app: alpine
      version: "1.0"
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: "40%"
      maxUnavailable: "40%"
  template:
    metadata:
      labels:
        app: jenkins
        version: "1.0"
    spec:
      containers:
        - name: "jenkins-con"
          image: jenkins/jenkins
      ports:
        - containerPort: 8080
          


      
